name: CI

on: push
       
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Fish
        run: |
          sudo apt-add-repository -yn ppa:fish-shell/release-3
          sudo apt-get update
          sudo apt-get install -y fish

      - name: Install Fisher
        run: curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher
        shell: fish {0}

      - name: Install Gitio
        run: $GITHUB_WORKSPACE/ && fisher install . && gitio https://github.com/jorgebucaran/gitio.fish
        shell: fish {0}
